= Quarkus Camel OOM issue

This project demonstrates [.line-through]#that the LRU cache used by an OGNL expression in the simple language does not use link:https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ref/SoftReference.html[soft references (`docs.oracle.com`)]# a OOM problem with camel.

We define a timer-triggered route that will set the body of the exchange to a large message. Then, we will access a field of that large object through OGNL:

.Timer Route
[source,java]
----
public class TimerRoute extends RouteBuilder {
  private final AtomicInteger calls = new AtomicInteger();

  private final MemorySize objectSize;

  ...

  @Override
  public void configure() {
    ...
    // @formatter:off
    from(timer("timer").delay(-1))
        .process(exchange -> {
          log.info("calls: {}", calls.incrementAndGet());
          exchange.getIn().setBody(new LargeObject(objectSize.asBigInteger().intValue()));
        })
        .log("${body.fieldTwo}");
    // @formatter:on
  }
}
----

The large object is just a simple, immutable POJO:

.Large Object
[source,java]
----
public class LargeObject {
  private static final Random RANDOM = new Random();

  byte[] data;
  String fieldOne;
  String fieldTwo;

  public LargeObject(int byteSize) {
    this.data = new byte[byteSize];
    RANDOM.nextBytes(data);
    fieldOne = UUID.randomUUID().toString();
    fieldTwo = UUID.randomUUID().toString();
  }
}
----

The default value for `objectSize` is `100M`, i.e. `100 * 1024 * 1024 = 104857600` bytes. The size can be configured by setting environment variable `OBJECT_SIZE` to, e.g., `1M`.

Notice that we do not hold a reference to the large object, we only print one of its fields through the OGNL expression in the simple expression.

== JVM Mode
=== Building the program
.Building the program
[source,bash]
----
./mvnw clean package
----

=== Running the program with `100M` object size, observing the error
For the test to end in a sensible amount of time, we need to limit the max heap of the VM. We will do so by setting JVM parameters `-XX:MinRAMPercentage` and `-XX:MaxRAMPercentage` to a sufficient low value. For my system (32 GB RAM), 10(%) has the desired effect. We also stop the program on the first `OutOfMemoryError` through `-XX:+ExitOnOutOfMemoryError`.

.Starting the program
[source,bash]
----
export OBJECT_SIZE=100M
java \
  -XX:MinRAMPercentage=10 \
  -XX:MaxRAMPercentage=10 \
  -XX:+ExitOnOutOfMemoryError \
  -jar target/quarkus-app/quarkus-run.jar
----

The execution results in the following logs:

.Execution log
[source]
----
...
2023-10-20 19:13:00,013 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 28
2023-10-20 19:13:00,641 INFO  [route1] (Camel (camel-1) thread #1 - timer://timer) e4310a3a-43d3-4415-9f97-21f2948b3eee
2023-10-20 19:13:00,641 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 29
2023-10-20 19:13:01,272 INFO  [route1] (Camel (camel-1) thread #1 - timer://timer) 132bf970-e53a-4d02-a55c-3111c7fd3903
2023-10-20 19:13:01,272 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 30
2023-10-20 19:13:02,220 INFO  [route1] (Camel (camel-1) thread #1 - timer://timer) e60f8d6f-920d-48ac-af6e-688fc709ae86
2023-10-20 19:13:02,221 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 31
2023-10-20 19:13:02,829 INFO  [route1] (Camel (camel-1) thread #1 - timer://timer) f274ef9c-b616-429c-8483-f7e232ea8a6f
2023-10-20 19:13:02,829 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 32
Terminating due to java.lang.OutOfMemoryError: Java heap space
----

=== Run the program with `1M` object size, observe no error
For the test to end in a sensible amount of time, we need to limit the max heap of the VM. We will do so by setting JVM parameters `-XX:MinRAMPercentage` and `-XX:MaxRAMPercentage` to a sufficient low value. For my system (32 GB RAM), 10(%) has the desired effect. We also stop the program on the first `OutOfMemoryError` through `-XX:+ExitOnOutOfMemoryError`.

.Starting the program
[source,bash]
----
export OBJECT_SIZE=1M
java \
  -XX:MinRAMPercentage=10 \
  -XX:MaxRAMPercentage=10 \
  -XX:+ExitOnOutOfMemoryError \
  -jar target/quarkus-app/quarkus-run.jar
----

Observe that the program keeps running, no `OutOfMemoryError` is thrown.

== Native Mode
=== Building the program
.Building the program
[source,bash]
----
./mvnw --define native clean package
----

=== Running the program with `100M` object size, observing the error
For the test to end in a sensible amount of time, we need to limit the max heap of the VM. We will do so by setting JVM parameter `-XX:MaximumHeapSizePercent` to a sufficient low value. For my system (32 GB RAM), 10(%) has the desired effect. We also stop the program on the first `OutOfMemoryError` through `-XX:+ExitOnOutOfMemoryError`.

.Starting the program
[source,bash]
----
export OBJECT_SIZE=100M
target/quarkus-camel-lru-cache-1.0.0-SNAPSHOT-runner \
  -XX:MaximumHeapSizePercent=10 \
  -XX:+ExitOnOutOfMemoryError
----

The execution results in the following logs:

.Execution log
[source]
----
...
2023-10-21 14:07:50,260 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 28
2023-10-21 14:07:50,623 INFO  [route1] (Camel (camel-1) thread #1 - timer://timer) e868c474-801d-42dc-92c7-28af5c4d8c39
2023-10-21 14:07:50,623 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 29
2023-10-21 14:07:50,982 INFO  [route1] (Camel (camel-1) thread #1 - timer://timer) 4af046de-6da4-4b65-82ae-764004ec0c47
2023-10-21 14:07:50,982 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 30
2023-10-21 14:07:51,366 INFO  [route1] (Camel (camel-1) thread #1 - timer://timer) 8e680efe-c6fd-4d55-8cc3-828c18a28fe3
2023-10-21 14:07:51,366 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 31
2023-10-21 14:07:51,729 INFO  [route1] (Camel (camel-1) thread #1 - timer://timer) e80fc719-b0ac-42f4-b9ca-b86c18d78f37
2023-10-21 14:07:51,729 INFO  [de.tur.TimerRoute] (Camel (camel-1) thread #1 - timer://timer) calls: 32
Terminating due to java.lang.OutOfMemoryError: Garbage-collected heap size exceeded.
----

=== Run the program with `1M` object size, observe no error
For the test to end in a sensible amount of time, we need to limit the max heap of the VM. We will do so by setting JVM parameter `-XX:MaximumHeapSizePercent` to a sufficient low value. For my system (32 GB RAM), 10(%) has the desired effect. We also stop the program on the first `OutOfMemoryError` through `-XX:+ExitOnOutOfMemoryError`.

.Starting the program
[source,bash]
----
export OBJECT_SIZE=1M
target/quarkus-camel-lru-cache-1.0.0-SNAPSHOT-runner \
  -XX:MaximumHeapSizePercent=10 \
  -XX:+ExitOnOutOfMemoryError
----

Observe that the program keeps running, no `OutOfMemoryError` is thrown.

== Further investigation
In the `1M`-case in JVM mode, if I lower the memory percentage to only 5% instead of 10%, I will, again, get the `OutOfMemoryError`, at around the 800th execution of the route. For the JVM-mode, I had to lower it to 3% to get the error to appear again. It then appears around the `970`th execution of the route.